apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-calc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-calc-deployment
  template:
    metadata:
      labels:
        app: go-calc-deployment
    spec:
      containers:
      - name: go-calc
        image: ${FINAL_IMAGE_NAME}
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-calc-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: go-calc-deployment