---
  name: CI 
  on:
    push:
      branches:
        - main
    pull_request:
  
  jobs:
    build-test-image:
      name: Build Image for Testing
      runs-on: ubuntu-latest
  
      permissions:
        packages: write 
  
      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
 
        - name: Login to ghcr.io
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build and Push to GHCR
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ghcr.io/iypetrov/go-calc:${{ github.run_id }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64 