---
  name: CI 
  
  on:
    push:
      branches:
        - main
    pull_request:
  
  jobs:
    build-test-image:
      name: Build Image for Testing
      runs-on: ubuntu-latest
  
      permissions:
        packages: write
  
      steps:
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        - name: Build and Push to Docker Hub 
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: iypetrov/go-calc:${{ github.run_id }}
            target: test
            platforms: linux/amd64