---  
  name: Auto Tag on Merge

  on:
    pull_request:
      types:
        - closed

  jobs:
    auto-tag:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name
        id: branch
        run: echo "::set-output name=branch::$(echo ${{ github.event.pull_request.head.ref }} | tr / -)"

      - name: Extract commit hash
        id: commit
        run: echo "::set-output name=commit::${{ github.event.pull_request.merge_commit_sha }}"

      - name: Create and push Git tag
        run: |
          git tag -a ${{ steps.branch.outputs.branch }} -m "Tag created on merge" ${{ steps.commit.outputs.commit }}
          git push origin ${{ steps.branch.outputs.branch }}
